# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Performance optimizations
add_newline = true
command_timeout = 1000
scan_timeout = 30

format = """
$directory\
$git_branch\
$git_status\
$character"""

right_format = """
$cmd_duration\
$time"""

[directory]
style = "blue"

[character]
success_symbol = "[ ❯](purple)"
error_symbol = "[ ❯](red)"
vimcmd_symbol = "[ ❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"
disabled = false

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = "[*](yellow) "
staged = ""
renamed = ""
deleted = ""
stashed = ""
diverged = " ⇡⇣"
ahead = " ⇡"
behind = " ⇣"
up_to_date = ""

[git_state]
disabled = true
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[cmd_duration]
disabled = false
format = "[$duration]($style) "
style = "yellow"

[python]
disabled = true
format = "[$virtualenv]($style) "
style = "bright-black"

[time]
disabled = false
format = '[$time]($style)'
time_format = '%T'
style = "bright-black"
